# Book settings
title: Quantitative Big Imaging - Dynamic experiments
only_build_toc_files: true

author: Anders Kaestner
#logo: 'images/logo.png'

execute:
  timeout: -1
  execute_notebooks: auto

latex:
  latex_documents:
     targetname: QBI-Lecture09-DynamicExperiments.tex
